services:
  laser-saber-customiser:
    image: laser-saber-customiser
    container_name: laser-saber-customiser
    # restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - generatedImages:/home/openscad/src/gen
volumes:
  generatedImages:
