### get parameter
GET http://localhost:8080/api/openscad/parameter

### 3DModel
POST http://localhost:8080/api/openscad/3DModel
content-type: application/json

[
  {
    "parameter": "zRot",
    "value": "60"
  },
  {
    "parameter": "allColors",
    "value": "orange"
  }
]

### preview
POST http://localhost:8080/api/openscad/preview
content-type: application/json

[
  {
    "parameter": "zRot",
    "value": "60"
  },
  {
    "parameter": "allColors",
    "value": "orange"
  }
]

### animation
POST http://localhost:8080/api/openscad/animation
content-type: application/json

[
  {
    "parameter": "zRot",
    "value": "60"
  },
  {
    "parameter": "allColors",
    "value": "orange"
  }
]
